sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

env:
  global:
    - CORE_BRANCH=stable9
  matrix:
    - DB=sqlite
    
branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh documents $CORE_BRANCH $DB

script:
  # Test lint
  - cd ../core/apps/documents
  - find . -name \*.php -exec php -l "{}" \;

  # Run phpunit tests
  - cd tests
  - phpunit --configuration phpunit.xml

  # Create coverage report
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != 'hhvm' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  
matrix:
  include:
    - php: 5.4
      env: DB=mysql
    - php: 5.4
      env: DB=pgsql
    - php: 5.4
      env: DB=oracle
  allow_failures:
    - php: hhvm
    - env: DB=oracle  # until it is fixed
  fast_finish: true
